type Props = {
    vin: string;
  };
  
  export default function VehicleHistoryPanel({ vin }: Props) {
    const cleanVin = vin?.trim() || "";
    const reportUrl = `/api/vin-report?vin=${encodeURIComponent(cleanVin)}`;
  
    return (
      <div className="rounded-2xl border bg-white p-5">
        <div className="text-2xl font-bold">Vehicle History</div>
  
        <p className="mt-2 text-sm text-gray-600">
          Open the full VIN report generated by your system.
        </p>
  
        <div className="mt-4">
          <a
            href={reportUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-block rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white"
          >
            Get Full VIN Report
          </a>
        </div>
      </div>
    );
  }